name: new test
on:
  workflow_dispatch:

  #schedule:
    #- cron: '5 */4 * * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Set timezone and Git configurations
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          
      - name: Install dependencies
        run: pip install requests

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Checkout repository qist/tvbox
        uses: actions/checkout@v4
        with:
          repository: qist/tvbox
          ref: master
          path: code
        
      - name: Run Python script
        working-directory: ${{ github.workspace }}
        run: |
          python ./${{ secrets.PY_PATH }}/dianshi.py

      - name: Check for changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "update"
          #commit_msg="更新并删除删除无效节点"
          #git commit -a --allow-empty -m "$commit_msg"

      - name: Push changes
        if: steps.check.conclusion == 'success'
        uses:  ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           # github_token: ${{ secrets.TOKEN }}
           branch: main
           #force: true
        #env:
          #GITHUB_ACTOR: ne7359

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        continue-on-error: true
        with:
          token: ${{ github.token }}
          repository: ${{github.repository}}
          retain_days: 0
          keep_minimum_runs: 1
