name: new
on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Set timezone and Git configurations
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          
      - name: Install dependencies
        run: pip install requests
        
  run_python_0821:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Checkout repository qist/tvbox
        uses: actions/checkout@v4
        with:
          repository: qist/tvbox
          ref: master
          path: code
        
      - name: Run Python script
        working-directory: ${{ github.workspace }}
        run: |
          python ./TVUrl-check/py/0821-A.py

      - name: Run Python script
        working-directory: ${{ github.workspace }}
        run: |
          python ./TVUrl-check/py/0821-B.py
       
      #- name: Save 0821-A.py result
        #run: |
          #cp ./out/0821.json ${{ github.workspace }}/0821.json

      - name: Upload 0821-A result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: 0821-result
          path: ${{ github.workspace }}/0821.json

  run_python_0825:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Checkout repository qist/tvbox
        uses: actions/checkout@v4
        with:
          repository: qist/tvbox
          ref: master
          path: code
        
      - name: Run Python script
        working-directory: ${{ github.workspace }}
        run: |
          python ./TVUrl-check/py/0825-A.py

      - name: Run Python script
        working-directory: ${{ github.workspace }}
        run: |
          python ./TVUrl-check/py/0825-B.py

      #- name: Save 0825-A.py result
        #run: |
          #cp ./out/0825.json ${{ github.workspace }}/0825.json

      - name: Upload 0825-A result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: 0825-result
          path: ${{ github.workspace }}/0825.json

  push_results:
    runs-on: ubuntu-latest
    needs: [run_python_0821, run_python_0825]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download 0821-A result
        uses: actions/download-artifact@v4
        with:
          name: 0821-result
          path: ./

      - name: Download 0825-A result
        uses: actions/download-artifact@v4
        with:
          name: 0825-result
          path: ./

      - name: Check for changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes detected. Skipping commit."
            exit 0
          fi
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "update"

      - name: Push changes
        if: steps.check.conclusion == 'success'
        uses:  ad-m/github-push-action@master
        with:
           # github_token: ${{ secrets.TOKEN }}
           branch: main

      - name: Delete artifacts
        run: |
          curl -X DELETE \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts
